# Generated by Django 4.1.1 on 2022-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=250)),
                ('price_usd', models.IntegerField()),
                ('price_rub', models.IntegerField()),
                ('order_date', models.DateTimeField()),
            ],
        ),
    ]
