# Generated by Django 4.1.1 on 2022-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price_rub',
            field=models.FloatField(),
        ),
    ]
