# Generated by Django 4.1.1 on 2022-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_ordermodel_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date',
            field=models.CharField(max_length=11),
        ),
    ]
